### ISSUE TITLE
EXTENDED_SECURITY and Client ntlmv2

### ISSUE THREAD

**Issue by ThError304** [thomasmauerer/hassio-addons#128]
Can you give us the option to change: 'client use spnego = yes' to no
And: 'client ntlmv2 auth = yes' to no

Thanks!

Because of the following error:
Server does not support EXTENDED_SECURITY  but 'client use spnego = yes' and 'client ntlmv2 auth = yes' is set
session setup failed: NT_STATUS_ACCESS_DENIED

**Comment by thomasmauerer** [comment]
I'm sorry, but I'm not going to implement that as these options are already deprecated and will be removed --> https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html#CLIENTUSESPNEGO

You should be thinking about using a different share since this means that your current one only supports an outdated authentication mechanism.
