### ISSUE TITLE
core_whisper backing up entire model

### ISSUE THREAD

**Issue by rwjack** [thomasmauerer/hassio-addons#172]
From my understanding, the model should be automatically excluded from the backup due to it's size.

Is this an HA issue, or could it be related to this addon?

**Comment by thomasmauerer** [comment]
I'm not using whisper myself, so I cannot tell whether this should be automatically excluded. However, it's for sure not an issue of Samba Backup since it calls the supervisor to create a backup. The functionality is exactly the same as if you would have created a backup manually from Home Assistant.

**Comment by rwjack** [comment]
Got it, thanks for the info!

**Comment by rwjack** [comment]
https://github.com/home-assistant/addons/issues/3577
