### ISSUE TITLE
Backup fails but tar file is present

### ISSUE THREAD

**Issue by nelbs** [thomasmauerer/hassio-addons#174]
After I replaced my Nas for a new one I have some issues with the samba backup. The backup fails, see log below, but the backup file is present on the samba share. 

![image](https://github.com/thomasmauerer/hassio-addons/assets/6464671/82ecc50b-c86a-43a8-8dcd-f1ea21620aaa)

Does anyone has a clue what goes wrong.

**Comment by Loic691** [comment]
Same for me

**Comment by GarethBlain** [comment]
I've found just that if you've moved your default backup location to a network storage using the new system added in the last few months this is the result. I guess it's looking on the old default location (local disk) which is empty.

Think this issue is a duplicate of: https://github.com/thomasmauerer/hassio-addons/issues/153

**Comment by nelbs** [comment]
@GarethBlain Thanks that is indeed the cause of the problem. I changed the default location to local and now it works again.
