### ISSUE TITLE
Empty files in Share on Synology...

### ISSUE THREAD

**Issue by deltabert** [thomasmauerer/hassio-addons#29]
I have for every backup also an empty share in an other directory under the Share on my Synology NAS.
Made a description about this on the Community Page.

Description: 
https://community.home-assistant.io/t/samba-backup-create-and-store-snapshots-on-a-samba-share/199471/158

Is this as intended? and if so, what is the function of these files?

**Comment by thomasmauerer** [comment]
It seems that you have some kind of "recycle bin feature" enabled on your NAS, which means that files are not actually deleted, but instead moved to that folder. Those files should already be deleted.

The samba-tmp123 is just an empty file which is created and deleted to check write-permissions. This happens if you (re)start the add-on.
