### ISSUE TITLE
Allow changing of Backup name

### ISSUE THREAD

**Issue by brucek1642** [thomasmauerer/hassio-addons#3]
This is an enhancement request.

Could you modify code to allow changing of the backup name. I would probably do something like this

name: 'Samba Backup pi4: {{ now().strftime(''%a, %b %-d %Y'') }}'

I am in the process of setting up two backups, on different days sending the backups to two different locations

Thanks, Bruce

**Comment by thomasmauerer** [comment]
The problem with custom names is that Samba Backup is then no longer able to clean up only those snapshots that were created with this addon. This does currently work because all snapshots have a fixed name pattern for which I can search.

I'm not sure yet if I should give up this behavior and instead clean up all snapshots. Then it's no problem to make the name customizable.

**Comment by N1c093** [comment]
Maybe you can do a mix of both? 
Have a static beginning "Automatic Backup" and have a variable ending.

So you can still cleanup every Backup which starts with "Automatic Backup"

**Comment by brucek1642** [comment]
Not a problem, leave as it is. Before submitting I quickly read through the code but did not look at the code to purge. My other backup does name differently so I can work with that.

Thanks, Bruce

**Comment by thomasmauerer** [comment]
I reopened this issue as I actually like the idea to make the names customizable. You can specify names when you manually trigger a snapshot, so this should be possible with this add-on as well.

**Comment by thomasmauerer** [comment]
Implemented in v2.0
