### ISSUE TITLE
Run partial backup with include_addons option?

### ISSUE THREAD

**Issue by lrybak** [thomasmauerer/hassio-addons#37]
Hello,

Would it be possible to trigger partial backup to do the backup for selected addon/s (as an opossite to exclude_addons)?
In my case I'm executing backup daily for all addons apart of influx which I need to run on weekly basis (due to big size and time needed). Is it somehow possible without using exclude_addons options and puting on the list all addons apart of influx ?

**Comment by thomasmauerer** [comment]
Hi. I'm actually not a big fan of having multiple config options for the same thing. Sure, both ways would work. It was more a design decision to make it excludable instead of includable.

I guess you are using a script and not doing this by hand. So it should only be a one-time effort to create the list of addons to be excluded.
