### ISSUE TITLE
No such image: thomasmauerer/samba-backup-armv7:4.4

### ISSUE THREAD

**Issue by AlexKnowsIt** [thomasmauerer/hassio-addons#43]
Since Home Assistant OS 5.11 (supervisor-2021.02.6) I can't start the add-on anymore. At startup it gives me the error message: `404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_15d21743_samba_backup: Not Found ("No such image: thomasmauerer/samba-backup-armv7:4.4")`

**Comment by thomasmauerer** [comment]
The image 4.4 is definitely available on Docker Hub. I could only imagine that you have a broken image on your system. Maybe caused by an interrupted download or something like this.

I would suggest to install the Portainer add-on and use it to completely remove the samba_backup image from your system. After that reinstall this add-on. Then it should fetch again the image from Docker Hub.

**Comment by AlexKnowsIt** [comment]
I will try that out later. Thanks for the fast response!

**Comment by AlexKnowsIt** [comment]
It works again :) Seems like a clean reinstall was all it needed. Thanks again for this amazing add-on!
